### ISSUE TITLE
api issue on user signUp

### ISSUE THREAD

**Issue by massivity** [aelassas/bookcars#46] opened 2024-01-18 13:14 UTC
Hello, While trying to install your solution locally to test it out,

It appears that in your documentation, at the admin sign-up part i am getting this error in the API containter : 

[user.signup] Échec de la requête dans la base de données :  [object Object] [Error: D07B66BCAAAA0000:error:0A000410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1586:SSL alert number 40
2024-01-18T13:10:02.844802500Z ] {
2024-01-18T13:10:02.844807708Z   library: 'SSL routines',
2024-01-18T13:10:02.844809333Z   reason: 'sslv3 alert handshake failure',
2024-01-18T13:10:02.844810833Z   code: 'ESOCKET',
2024-01-18T13:10:02.844812583Z   command: 'CONN'
2024-01-18T13:10:02.844813916Z }

can you help?

**Comment by aelassas** [comment] 2024-01-18 13:59
Are you using Docker and SSL?

**Comment by massivity** [comment] 2024-01-18 14:08
> Are you using Docker and SSL?

Currently Docker but no SSL

**Comment by aelassas** [comment] 2024-01-18 14:56
The error you are getting is either related to MongoDB or SMTP.

Once the user is created in MongoDB, an activation email is sent automatically.

To eliminate MongoDB case, start your MongoDB container, open MongoDB Compass, connect to your MongoDB container, and check whether your admin user has been created in User collection in bookcars database.

If your admin user has been created, the error is related to SMTP. Check that the SMTP settings are correct and are working in api/.env.docker:
```
BC_SMTP_HOST=in-v3.mailjet.com
BC_SMTP_PORT=587
BC_SMTP_USER=USER
BC_SMTP_PASS=PASSWORD
BC_SMTP_FROM=admin@bookcars.ma
```
You can use sendgrid, mailjet or any other SMTP provider.

**Comment by massivity** [comment] 2024-01-18 17:43
For a reason I can't guess, I cannot reach the mongoDB server at all. It seems to be running, but no tools cannot reach it neither compass.

**Comment by aelassas** [comment] 2024-01-18 21:02
Check that MongoDB container is running on Docker desktop on port 27017, then if you have set up the password you should be able to connect through MongoDB Compass on `mongodb://admin:PASSWORD@localhost:27017/`.
I have tested the connection on my side and it's working but I am using Windows.

**Comment by aelassas** [comment] 2024-01-25 11:41
@massivity Another way to check wether the issue is related to MongoDB is to run the app, go to admin sign up page and fill the form with the same email you entered the first time. If you get that the email is already registered this means that MongoDB is working and that the issue is related to smtp config.

**Comment by aelassas** [comment] 2024-01-26 15:31
I am closing this issue because I didn't get any response from you. Your issue is certainly related to smtp config in the api.

**Closed by aelassas** 2024-01-26 15:31 UTC
